# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbit-sentinel-mcp" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6a08f42d724ca191deec2f0d6c541313304ffab3dc740ec24b60fa6c5e73280b"
      url "https://github.com/acaracappa/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e58b8245d6506149751f393870d05d3454b5b9f017e614acdb3b36249ea16b4"
      url "https://github.com/acaracappa/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7e8caa4ada1c5f1fb10f5a61eaff1d27ae7623f91b139f7185ccb6e41fb2a77"
      url "https://github.com/acaracappa/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "077e4412bbd103ea3c15088080d0acf0906533291bf92aa5743f02956cad4cb3"
      url "https://github.com/acaracappa/orbit-sentinel-mcp/releases/download/v#{version}/orbit-sentinel-mcp_linux_arm64.tar.gz"
    end
  end

  name "orbit-sentinel-mcp"
  desc "MCP server for Orbit Sentinel — space regulatory filings from FCC, ITU, UNOOSA, FAA-AST"
  homepage "https://github.com/acaracappa/orbit-sentinel-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbit-sentinel-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orbit-sentinel-mcp"]
    end
  end

  # No zap stanza required

end
